### PR TITLE
Use newer _POSIX_C_SOURCE to work with GCC 14.0+

### PR DESCRIPTION
**Pull request by ilvez**
Since GCC 14 makes `-Wimplicit-function-declaration` and `-Wint-conversion` manifest as errors, we need to actually include newer POSIX version that actually exposes 'strdup' as function, instead of relying it getting included implicitly. Otherwise compiling scrypt with GCC 14.0+ fails.

Without this change we can see warnings(on GCC < 14)/errors (on GCC 14+) as part of compilation:
```
ext/scrypt/warnp.c: In function ‘warnp_setprogname’:
ext/scrypt/warnp.c:39:16: warning: implicit declaration of function ‘strdup’; did you mean ‘strcmp’? [-Wimplicit-function-declaration]
   39 |         name = strdup(p);
      |                ^~~~~~
      |                strcmp
ext/scrypt/warnp.c:39:14: warning: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   39 |         name = strdup(p);
      |              ^
```

With newer POSIX version, just compiles no errors:
```
gcc -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std\=c99 -msse -msse2 -D_POSIX_C_SOURCE\=200809L -fPIC -o ext/scrypt/x86_64-linux/warnp.o -c ext/scrypt/warnp.c
```

Resources:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96284
- https://stackoverflow.com/a/26285540/925315

### CODE REVIEW

**Comment by ilvez** [comment]
@johanns Based on this comment https://github.com/pbhogan/scrypt/issues/85#issuecomment-1099595423 I'm assuming you are currently maintaining this this gem. Can you review please?
